### ISSUE TITLE
[Bug] Properties not appearing in context menu with auto complete.

### ISSUE THREAD

**Issue by DigitalPotatoBits** [majusko/pulsar-java-spring-boot-starter#131]
When including your library, the application properties are not recognized by Intellij. When entering a property in the application.properties file, you have to constantly refer to the Properties class because there is not a drop down context menu with auto-complete. 

When trouble shooting this issue, this is what I found.

- In the PulsarJavaSpringBootStarterApplication class, we need to add the "@ConfigurationPropertiesScan" annotation. This alone did not fix the issue.

- In the PulsarAutoConfiguration class, we need to delete the "ConsumerProperties.class" from the annotation. 

This will now let Intellij show the pulsar properties in the context menu, however, now the tests fail for the application. I am new to spring development and don't know how to fix this :/

**Comment by majusko** [comment]
Hi @DigitalPotatoBits , thank you for the issue. Will have a look into this. Feel free to publish PR in case you find out.

**Comment by majusko** [comment]
Hi @DigitalPotatoBits, Just tested in the project and also in the example project and autocomplete works just fine. 

Feel free to try it yourself: https://github.com/majusko/java-pulsar-example
