### ISSUE TITLE
Read me needs updating

### ISSUE THREAD

**Issue by DigitalPotatoBits** [majusko/pulsar-java-spring-boot-starter#133]
When attempting to follow the read me for getting an example application up and running, there are several syntax errors.  Some of the code snippets call functions that should throw exceptions for example.

**Comment by majusko** [comment]
Hi @DigitalPotatoBits thank you for the feedback. Where exactly do you think there is an issue? Feel free to update PR with improvement. Did you also tried an example project https://github.com/majusko/java-pulsar-example  - there is also an integration tests example with a real pulsar docker instance.

**Comment by DigitalPotatoBits** [comment]
Hey @majusko sorry about the late response. Our team is mostly new developers and when following the readme exactly, i.e. copy pasta the code into our own project, we would get snytax errors. For example, the code snippet in section 2 needs to have a throws exception for the send method, same for the code snippet in section 3, if memory serves. With regards to the example project, you have an AtomicBoolean which is nowhere to be seen in the readme. At my organization, we are not allowed to pull code from git repo, so we could not test the example project. Corporate red tape :'(

**Comment by majusko** [comment]
Hey @DigitalPotatoBits - I updated the README and tested the example. All should be clear now and all should also compile. Hope it's much better now :) Thank you for the feedback.

 https://github.com/majusko/pulsar-java-spring-boot-starter/pull/141
