### ISSUE TITLE
reactor-core maven dependency transfer problem 

### ISSUE THREAD

**Issue by Ulicong** [majusko/pulsar-java-spring-boot-starter#150]
Dependency transfer problem 
  ```
<dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>3.4.9</version>
  </dependency>
```

**environment：**

 ```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.1.RELEASE</version>
    </parent>

 spring-boot-dependencies-2.1.1.RELEASE.pom

    <dependency>
          <groupId>io.projectreactor</groupId>
          <artifactId>reactor-bom</artifactId>
          <version>Californium-SR3</version>
           <type>pom</type>
          <scope>import</scope>
  </dependency>

<dependency>
        <groupId>io.projectreactor</groupId>
        <artifactId>reactor-core</artifactId>
        <version>3.2.3.RELEASE</version>
        <scope>compile</scope>
 </dependency>
```

**Comment by Ulicong** [comment]
If i am setting <reactor-bom.version>2020.0.10</reactor-bom.version> in my  pom  is run ok but destroy the original version dependency will cause some problems？

**Comment by Ulicong** [comment]
```
    private final Sinks.Many<FailedMessage> sink = Sinks.many().multicast().onBackpressureBuffer(Queues.SMALL_BUFFER_SIZE, false);

sink.tryEmitNext(new FailedMessage(e, consumer, msg));

```

What does this code do？

**Comment by majusko** [comment]
Hi @Ulicong `Sink` is used to have the possibility to subscribe for the exceptions from the aggregator and implement error logging if needed. 

`Sink` was introduced in later versions of the reactor core. `EmitterProcessor` was the option before but it became deprecated and that is why you probably have compile problems when removing the newer reactor-core version.

Initially, I wanted to add more `reactor-core` use cases but I think it's not something that people need or request right now so I'm now thinking about removing this and not using this robust library for this use case. Is there any workaround you found out that work for you?

**Comment by almogtavor** [comment]
@Ulicong why won't you just use the latest version? @majusko I agree with you about adding more functionality for the library.
No reason to remove the usage of Reactor because of this issue.

**Comment by majusko** [comment]
Closing due to ongoing reactor core implementation in 1.1.0.
