### ISSUE TITLE
[FEATURE] - Listener annotation improvement request

### ISSUE THREAD

**Issue by ThePotatoProgrammer** [majusko/pulsar-java-spring-boot-starter#153]
Our team would like the ability to do the following:

`@Value("${pulsar.subscription-name}")`
`private String SUBSCRIPTION_NAME;`
`@PulsarConsumer(topic = "${pulsar.topic"}, subscriptionName = SUBSCRIPTION_NAME)
`private void consume(...)`

We would like to read a property from the application.properties file and then inject the value into the subscriptionName field.
The Issue here is that the annotation says that the subscription name needs to be const. 

Note: the `topic = "${pulsar.topic"}` part already works.

**Comment by majusko** [comment]
Good point. Thank you. I will add SpEL support to subscription names and consumer names as well.

**Comment by majusko** [comment]
Will be released in `1.0.7`
