### ISSUE TITLE
[BUG] - Begin consuming messages after spring boot startup is complete

### ISSUE THREAD

**Issue by ThePotatoProgrammer** [majusko/pulsar-java-spring-boot-starter#154]
When we launch our app, there are messages that the listener consumes before the start up finishes. We would like the listener to only consume message after startup is complete. Not sure if this is a bug.

**Comment by majusko** [comment]
Thanks for reporting this. I don't think it's a bug but I can imagine it would help in case of stateful services. I will have a look at this and lt you know.

**Comment by majusko** [comment]
Fix will be released in `1.0.7`
