### ISSUE TITLE
[FEATURE] - Add subscription type to properties

### ISSUE THREAD

**Issue by ThePotatoProgrammer** [majusko/pulsar-java-spring-boot-starter#155]
After implementing the pulsar listener, my team ran into an issue during testing. The issue is that consumer names are exclusive when the subscription type is exclusive so only one app can run at a time. With the current implementation, if you have an application that gets pushed to the cloud, now you can't have multiple instances, because the default subscription type is exclusive, and the consumer name would be the same for each instance of the app. 

We changed our listener subscription type to be shared and now multiple people can test using the same consumer name. This is important for final production release. Round robin messaging though, so it is still annoying for local/dev testing, not sure you can do anything about that part though.

We are not sure if this is the best solution.

**Comment by majusko** [comment]
Option to override default subscription type will be available in `1.0.7 `. You just need to set `pulsar.consumer.default.subscription-type` to `Shared` or `Exclusive`. Hope this will help. Everything is backwards compatible.
