### ISSUE TITLE
[FEATURE] - Add OAuth2 support.

### ISSUE THREAD

**Issue by ThePotatoProgrammer** [majusko/pulsar-java-spring-boot-starter#172]
https://pulsar.apache.org/docs/en/security-oauth2/

Leadership decided that they would also like the option to authenticate using OAuth2. Currently, I don't think that that this library supports that ability. Would it be possible to add it?

Also, if this is possible, my lead dev would like the option to assign the properties used for the OAuth2 in the application.properties file.

**Comment by majusko** [comment]
This feature will be released in 1.0.8

In case you need this implementation right now, feel free to use commit build in Jetpack repo:

```
	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>

	<dependency>
	    <groupId>com.github.majusko</groupId>
	    <artifactId>pulsar-java-spring-boot-starter</artifactId>
	    <version>1084666ffb</version>
	</dependency>
```
