### ISSUE TITLE
It is recommended to optimize the Consumer Collector

### ISSUE THREAD

**Issue by sivern** [majusko/pulsar-java-spring-boot-starter#210]
It is recommended to increase the cache of non-singleton mode beans in ConsumerConnector, so that the framework can affect the initialization of beans as little as possible.
` @Override
    public Object postProcessBeforeInitialization(Object bean, String beanName) {
        final Class<?> beanClass = bean.getClass();
        if (this.nonAnnotatedClasses.contains(beanClass)) {
            return bean;
        }

        consumers.putAll(Arrays.stream(beanClass.getDeclaredMethods())
                .filter($ -> {
                    if (!$.isAnnotationPresent(PulsarConsumer.class)) {
                        this.nonAnnotatedClasses.add(bean.getClass());
                        this.logger.trace(() -> "No @PulsarConsumer annotations found on bean type: " + bean.getClass());
                        return false;
                    }
                    return true;
                })
                .collect(Collectors.toMap(
                        method -> urlBuildService.buildConsumerName(beanClass, method),
                        method -> new ConsumerHolder(method.getAnnotation(PulsarConsumer.class), method, bean,
                                SchemaUtils.getParameterType(method)))));

        return bean;
    }`

**Comment by majusko** [comment]
Good idea. Will have a look into this.
