### ISSUE TITLE
repeat consume

### ISSUE THREAD

**Issue by wangjuqing** [majusko/pulsar-java-spring-boot-starter#233]
pulsar service started by standalone. When client service restart, the client consumer can receive previous messages.

"batchingEnabled":true, and acknowledgmentAtBatchIndexLevelEnabled=true

how to solve this problem？

**Comment by wangjuqing** [comment]
https://github.com/majusko/java-pulsar-example

This demo restart also repeat consume. The log repeat output.

**Comment by wangjuqing** [comment]
in this demo,consume how to Acknowledge message.

**Comment by wangjuqing** [comment]
https://github.com/majusko/java-pulsar-example

This demo restart also repeat consume. The log repeat output.
------------------------------------------------------------------

Sir: How to solve this problem? repeat consume: log repeat output.

**Comment by wangjuqing** [comment]
SIr: Whether the repeated  is because there is no Ack message?
How to  invoke io.github.majusko.pulsar.consumer.DefaultConsumerInterceptor#onAcknowledge?
demo application doesn't invoke onAcknowledge.

Looking forward to your reply.

**Comment by wangjuqing** [comment]
Sir: in try code block whether need invoke consumer.acknowledge()?
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/11013142/162204945-37fb94db-427f-4d5e-a0e5-af538f7c58be.png">

**Comment by majusko** [comment]
Aaah thanks @wangjuqing ... I had a long message with a lot of explanations prepared but this is a bug that happened during the merge of a merge conflict. Not sure why tests passed. Will try to do a test case for this use case. I will release the hotfix soon. THANK YOU!

**Comment by majusko** [comment]
Use version `1.1.0` for now.

**Comment by majusko** [comment]
Hotfix `1.1.2` has been released and is ready to be used with Jitpack now or with Maven in a few hours. I also updated the example project. Sorry for the inconvenience, and thank you very much for finding this bug! 🙌 👏

I will add a few test cases to cover a case with ack missing tmr.

**Comment by wangjuqing** [comment]
Thanks 😄
