### ISSUE TITLE
[FEATURE] - Consumer method with ack/negative ack

### ISSUE THREAD

**Issue by gmendoza-wenance** [majusko/pulsar-java-spring-boot-starter#276]
Hi, is possible to manage consumer communication from a method consumer?

I need to send a negative ack when the business constraint fail
Maybe already exists but I don't read nothing about it in the docs 

Thanks in advance

**Comment by majusko** [comment]
Hey, this is currently not possible using the annotated method. You can use a Flux approach as a workaround. It seems that there is increased demand for this feature, so we may increase the priority for this and implement the option to manually ack messages if some configuration is set.

**Comment by majusko** [comment]
You can achieve this in batch consuming from version `1.2.0`.

Docs: https://github.com/majusko/pulsar-java-spring-boot-starter#7-configure-batch-consumer-with-manual-acknowledge-control

`1.2.0` Has been released.
