### ISSUE TITLE
About automatic ack

### ISSUE THREAD

**Issue by dsj017112** [majusko/pulsar-java-spring-boot-starter#319]
Hello! majusko

At present, can our message listening annotations support manual "ACK", because automatic "ACK", if the business logic processing exception, then it may cause message loss.

Looking forward to your reply!
Thanks!

**Comment by majusko** [comment]
You can achieve this in batch mode which is going to be in the next release - it's already merged in the `master` branch and the docs are here:

https://github.com/majusko/pulsar-java-spring-boot-starter#7-configure-batch-consumer-with-manual-acknowledge-control

**Comment by majusko** [comment]
`1.2.0` Has been released

**Comment by dsj017112** [comment]
hi&nbsp;majusko


Very glad to receive your reply！


Thank you, did you solve my problem!




If there were any WeChat, we can communicate in WeChat in the future。 Ha ha~


ddd017112&nbsp;This is my WeChat&nbsp;



Or do you have any social software, I contact you


Shijia 2023/1/6 20:05(Beijing time.)








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "majusko/pulsar-java-spring-boot-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月6日(星期五) 晚上7:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [majusko/pulsar-java-spring-boot-starter] About automatic ack (Issue #319)





 
1.2.0 Has been released
