### ISSUE TITLE
SPEL for topic name

### ISSUE THREAD

**Issue by TrashCoder96** [majusko/pulsar-java-spring-boot-starter#40]
Hi, majusko!
What about SPEL-support to set topic name in @PulsarConsumer annotation? It would be convenient to use SPEL to extract topic name from application.yaml.

**Comment by majusko** [comment]
Thanks for the great idea. I will try to implement during next rainy weekend 😊

**Comment by majusko** [comment]
Support for producer here: https://github.com/majusko/pulsar-java-spring-boot-starter/issues/45
