### ISSUE TITLE
Streaming feature

### ISSUE THREAD

**Issue by TrashCoder96** [majusko/pulsar-java-spring-boot-starter#46]
Hi, majusko!
Do you plan on implementing streaming feature? For example, support Apache Flink or other frameworks for dataflow processing.

**Comment by majusko** [comment]
Hi @TrashCoder96 ,
Yes, adding streaming support sounds like something to implement. What do you think is the most important features in streaming and is there any other library for streaming that you think might be an inspiration?

**Comment by TrashCoder96** [comment]
Our team is working on integration beetween Pulsar and Apache Flink for our Spring Boot microservices. If all goes well, we will create pull request to your library, if you wish. Actually we are inspired by libraries for Apache Kafka and we are trying to follow their ideas. Also we are trying to use this connector https://github.com/streamnative/pulsar-flink for Flink. There is many features supported by this connector but we havent with the yet

**Comment by majusko** [comment]
Perfect, that sounds smart to me. Let's cover the basic usage first.

**Comment by TrashCoder96** [comment]
I thought for a long and i came to think that it should be separate library specially designed for streaming. Pulsar Starter is not appropriate in this aspect.

**Comment by majusko** [comment]
Yes, agree. I also wanted to suggest a separate library for such a project first but I could also imagine having a simple connector for streaming in the library for the easy bootstrap of any Pulsar project the "Spring Boot way" and then wrapping more functionality in a separate library. 

I will do the same with event sourcing support. I will do a Pulsar Event Source library that will make any microservice communication smoother and will focus on interservice communication, events and commands as described in CQRS architectures using this starter as a base library.

**Comment by TrashCoder96** [comment]
Thank you very much for your work) i will follow
