### ISSUE TITLE
Allow async send and message configuration

### ISSUE THREAD

**Issue by thiagolocatelli** [majusko/pulsar-java-spring-boot-starter#55]
I am wondering if you would be interested in a pull request that includes async send and message configuration to the `PulsarTemplate` like in the Pulsar documentation:

Async send:
```
producer.sendAsync("my-async-message".getBytes()).thenAccept(msgId -> {
    System.out.printf("Message with ID %s successfully sent", msgId);
});
```

Message configuration:
```
producer.newMessage()
    .key("my-message-key")
    .value("my-async-message".getBytes())
    .property("my-key", "my-value")
    .property("my-other-key", "my-other-value")
    .send();
```

If you are interested, I can work on it and send a PR soon. Thank you

**Comment by thiagolocatelli** [comment]
I sent the pull request, but now I am thinking. The `createMessage` would only make sense if we are able to create a consumer that receives an `Message<T>` instead of the pojo, this way the consumer can look at the message properties. Something like this:

```java
@PulsarConsumer(topic = "topic-message", clazz = MyMsg.class, serialization = Serialization.JSON)
public void topicMessageListener(Message<MyMsg> message) {
    Assertions.assertNotNull(message.getProperty("my-key"));
}
```

Trying to think how I can make that happen by changing the `ConsumerCollector` class.

**Comment by majusko** [comment]
Hey @thiagolocatelli. Both ideas are valid and make sense. I will try to describe how would I achieve both of them and we can discuss if you disagree or you can start working on any of them right away if you are ok with it 😊

1. There is 'reactor-core' library already as a dependency and I think the async should be done using this library wrapping the blocking into Mono. For the future, I wanted to implement a new feature where you can subscribe to a topic using a reactive stream.

2. This is a good point and I was thinking about it. At first, I wanted to wrap the management of the message inside the library so the user of the library does not need to think about when and how should be message acknowledged and it's clear for everyone that it's solved for them. However, I agree it might be limiting for some use cases and I have an idea how could we fix this. I would create a custom `Message` wrapper that consist of the value + properties(or other valuable information that is stored in pulsar `Message`) but would not return the "raw" Pulsar `Message` so it's still clear for the user that it's acknowledged for them and would make it hard for them to break the behaviour of the library.

**Comment by thiagolocatelli** [comment]
I like both approaches. I will think of how number 2 can be implemented. I think if we check the parameter of the method that is consuming the message we can either use the customer `Message` object or just use `msg.getValue`.

**Comment by majusko** [comment]
I will try to help with this:

1. You will need to create holder `PulsarMessage<T>` 
2. Add new attribute into `ConsumerHolder` that informs if the invoked method is wrapped or not.
3. Check if the type of the parameters in method match with `PulsarMessage`using reflection inside `ConsumerCollector` and store it into `ConsumerHolder`
4. In `ConsumerBuilder` you will send wrapped or unwrapped messages depending on the information stored in `ConsumerHolder` 
5. Write a test to cover thisusecase.

Also, leave the Async support on me. I will do that today if you don't mind because I noticed that `EmitterProcessor` is being deprecated and will also do a replacement of that for the next release.

**Comment by thiagolocatelli** [comment]
sounds like a plan. I am going to try to finish today if I can get the baby to sleep long enough! :)

Also, I was thinking that since I am going to be touching the ConsumerHolder, maybe the `clazz` attribute of the annotation is not necessary anymore since we can infer the type of the message (wrapped or unwrapped) based on the method parameter.

```java
Method[] methods = SampleClass.class.getMethods();
Class[] parameterTypes = methods[1].getParameterTypes();
```

It would prevent use cases like this. The library should not allow this to happen, even if it allowed the code to be written this way, it should stop the application from starting up. Are you ok with me removing the `clazz` attribute and infer from the method parameter?

```java
    @PulsarConsumer(topic = "topic-for-error", clazz = String.class, serialization = Serialization.JSON)
    public void topicForErrorListener(Integer myMsg) {
    }
```

We could also enforce the method having only one parameter, display an error message in the log and not create the consumer. Any ideas?

**Comment by thiagolocatelli** [comment]
The pull request has been updated with `PulsarMessage` change. I did not remove the `clazz` from the `@PulsarConsumer` annotation since I figured it would require more code change when we use `PulsarMessage<T>`, I would have to read the generic type from the PulsarMessage in order to create the schema for the consumer. I will do that next.

**Comment by majusko** [comment]
Good points @thiagolocatelli and glad you could make the PR before the baby got up 😀  . It would be a very nice feature indeed to remove the `clazz` parameter requirement from the annotation. Code you did is clean and It looks great so I merged to master. Good job and thanks for your contribution! 🥳 🙇‍♂️ 🥇

**Comment by majusko** [comment]
Creted an issue that covers the `clazz` change:

**Comment by thiagolocatelli** [comment]
@majusko Thank you, sir. I will start thinking on the new issue and will try to get it done this week for you.

**Comment by thiagolocatelli** [comment]
@majusko I will send a PR soon to update the documentation as well.
