### ISSUE TITLE
Add support for pulsar-admin apis 

### ISSUE THREAD

**Issue by Andreby42** [majusko/pulsar-java-spring-boot-starter#59]
should we  support pulsar admin apis ? so we can dynamic  do somthing .

**Comment by majusko** [comment]
Sorry @Andreby42 , what do you mean by pulsar admin? Can you maybe try to explain by answering these four questions?:

1. What you mean by pulsar-admin? (Maybe link to the library)
2. How would the support look like?
3. Wouldn't separate library make more sense?
4. What use case is the support of "pulsar admin api" solving?

**Comment by Andreby42** [comment]
I mean  Pulsar Client Admin 
1.http://pulsar.apache.org/docs/en/pulsar-admin/ this is Pulsar admin CLI, also  there is a  java implements , https://mvnrepository.com/artifact/org.apache.pulsar/pulsar-client-admin 
2.we can use pulsar client admin apis to do something, such as multi-tenancy , auto init tenant and topics get more server info .etc
3. U think admin apis should not in this project?  it should be another starter? ok.
4. see @2.
 Thanks for your prompt reply, this is just my suguest。/lol

**Comment by majusko** [comment]
I'm glad you did the suggestion for an enhancement. I just needed to understand the proposal better and that is why I asked the questions 😊 Thanks for the reply, I will do a research on it but I think the better approach would be a separate starter. But let me do research first 🙇‍♂️

**Comment by Andreby42** [comment]
well,thanks for your reply, Ur code is excelent, I learn a lot from Ur code.😊

**Comment by majusko** [comment]
I consider Pulsar admin CLI as not suitable for a use case that this library is trying to solve. It will be better to move such functionality into separate spring-boot-starter mostly because by design you should have a separate cluster setup for Pulsar and your business application should not be able to access pulsar by command line.
