### ISSUE TITLE
Subscription name

### ISSUE THREAD

**Issue by dmarko484** [majusko/pulsar-java-spring-boot-starter#87]
I would like to use SHARED subscription type for several consumers for round-robin delivery. To get this working one has to specify the same subscription name, but I can't find how to define this. I can see subscription name is created based on class + method name so basically every consumer creates unique subscription, see screenshot below. Is there a way how to achieve this?

![image](https://user-images.githubusercontent.com/145922/106247875-76610280-6210-11eb-9475-e11ec88ebf18.png)

**Comment by majusko** [comment]
Definitely should work for horizontal scaling (same app -> multiple instances). However, do I understand this correctly and you are trying to achieve multiple shared subscriptions inside one application? If it's the case, can you please describe your use case more closely? I can imagine adding an option to override the subscription and consumer names in `PulsarConsumer` annotation but didn't meet with such use case so it's not supported at the moment.

**Comment by majusko** [comment]
Done, will be released in 1.0.6
