### ISSUE TITLE
when 2 or more consumers，Every consumer will consume once.

### ISSUE THREAD

**Issue by sundong1982** [majusko/pulsar-java-spring-boot-starter#94]
If I want to execute only once, no matter how many nodes. How to solve it?

**Comment by majusko** [comment]
Hey @sundong1982, so you would like every node/pod in the cluster to receive the message? This should work with an `Exclusive` subscription but I'm gonna check if it's implemented this way.

**Comment by sundong1982** [comment]
i tried subscriptionType = SubscriptionType.Shared,    but multiple application subscribed to the same topic,still not just once.

**Comment by majusko** [comment]
Sorry @sundong1982  but this is intended behaviour by Pulsar documentation https://dattell.com/data-architecture-blog/subscription-types-in-apache-pulsar/

You should use `Exclusive` to cover your use case :) 

Closing this.
